// AUTO-GENERATED by scripts/generate-data.mjs - do not edit by hand.
// Regenerate with: npm run generate

/** English local level name suffixes, indexed from 1 in the encoded records. */
export const EN_SUFFIXES: readonly string[] = ["Sub-Metropolitian City","Rural Municipality","Metropolitian City","Sub-Metropolitan City","Metropolitan City","Municipality"];

/** Nepali local level name suffixes, indexed from 1 in the encoded records. */
export const NE_SUFFIXES: readonly string[] = ["उपमहानगरपालिका","महानगरपालिका","गाउँपालिका","गाउंपालिका","नगरपालिका"];

