// AUTO-GENERATED by scripts/generate-data.mjs - do not edit by hand.
// Regenerate with: npm run generate

/**
 * Every Devanagari character used by the dataset, in the order the packed
 * records reference them.
 */
export const NE_ALPHABET: string = " ()-.ँंअआइईउऋएऐओऔकखगघङचछजझञटठडढणतथदधनपफबभमयरलवशषसहािीुूृेैोौ्०‍";

/**
 * ASCII stand-ins for {@link NE_ALPHABET}, position for position. Packed Nepali
 * fields contain only these characters, one byte each.
 *
 * Kept separate from the local level suffix dictionaries so that the province and
 * district entry points do not have to load them.
 */
export const NE_POOL: string = "#$%&()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abc";
