// AUTO-GENERATED by scripts/generate-data.mjs - do not edit by hand.
// Regenerate with: npm run generate

/** `nameEn|nameNe|districtCount` per line, ordered by province code (1-based). */
export const PROVINCE_DATA: string = 'Koshi Province|5_RX#IaOF]R|e\nMadhesh Province|MG]R#IaOF]R|8\nBagmati Province|KV7MDX#IaOF]R|d\nGandaki Province|7CaA5X#IaOF]R|b\nLumbini Province|PYMaKWHX#IaOF]R|c\nKarnali Province|5OaCVPX#IaOF]R|a\nSudurpashchim Province|TYFZOIRa:WM#IaOF]R|9';
